# Aquí están definidos todos los parámetros utilizados para que sean importados en los
# otros programas
DEUDA_TOTAL = 8000
PROBABILIDAD_EVENTO = 0.15
PORCENTAJE_APUESTA_TACANO = 50
BONIFICACION_TACANO = 10
FRUSTRACION_PERDER = 2
CONFIANZA_PERDER = 2
EGO_GANAR = 2
CARISMA_GANAR = 3
FRUSTRACION_GANAR = 2
BONIFICACION_SUERTE_CASUAL = 2
MULTIPLICADOR_BONIFICACION_BEBEDOR = 3

DINERO_SHOW = 100
ENERGIA_SHOW = 15
FRUSTRACION_SHOW = 10
